# Generated by Django 4.0.6 on 2022-07-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0002_initial'),
        ('students', '0002_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='semesters.semester'),
        ),
    ]
