# Generated by Django 4.0.6 on 2022-07-12 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
