# Generated by Django 4.0.6 on 2022-07-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_teacher'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
