# Generated by Django 4.0.6 on 2022-07-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='subjects_id',
            field=models.ManyToManyField(related_name='semester', to='subjects.subject'),
        ),
    ]
